### ISSUE TITLE
NodeJS dependency issue

### ISSUE THREAD

**Issue by bertux** [pchain-org/wallet#11]
When following the initialization procedure on Ubuntu 18.04.2 I receive this error :
yarn start
yarn run v1.15.2
$ electron .
App threw an error during load
Error: Cannot find module '/home/bjuglas/Documents/Pchain/wallet/node_modules/sqlite3/lib/binding/electron-v3.0-linux-x64/node_sqlite3.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/bjuglas/Documents/Pchain/wallet/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/bjuglas/Documents/Pchain/wallet/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Object.<anonymous> (/home/bjuglas/Documents/Pchain/wallet/node_modules/sqlite3/lib/sqlite3.js:190:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/bjuglas/Documents/Pchain/wallet/sqlite3/dbInit.js:6:15)
    at Object.<anonymous> (/home/bjuglas/Documents/Pchain/wallet/sqlite3/dbInit.js:127:3)

**Comment by bertux** [comment]
ls /home/bjuglas/Documents/Pchain/wallet/node_modules/sqlite3/lib/binding/
node-v57-linux-x64

**Comment by bertux** [comment]
The solution seems to be https://stackoverflow.com/questions/32504307/how-to-use-sqlite3-module-with-electron so I'm trying it.

**Comment by bertux** [comment]
I have corrected it and submitted the pull request https://github.com/pchain-org/wallet/pull/12
